name: go vet test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:

  statictest:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "auto"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: Verify dependencies
        run: go mod verify

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/tools/statictest

      - name: Run statictest
        run: |
          go vet -vettool=./tools/statictest ./...
